"""empty message

Revision ID: 73d9d72d1cb9
Revises: 2513b921efb9
Create Date: 2022-03-15 19:43:17.838942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d9d72d1cb9'
down_revision = '2513b921efb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('ability1', sa.String(length=300), nullable=True),
    sa.Column('ability2', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
