"""empty message

Revision ID: ce50d98c3373
Revises: 73d9d72d1cb9
Create Date: 2022-03-16 06:16:30.468651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce50d98c3373'
down_revision = '73d9d72d1cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('ability3', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'ability3')
    # ### end Alembic commands ###
